### PR TITLE
Collapse rapid-fire notifications

### PR DESCRIPTION
**Pull request by UInt2048**
Sometimes, users receive lots of rapid-fire notifications, such as 20 notifications in one minute.

This PR allows users to collapse notifications when above a threshhold to make viewing logs more manageable.

### CODE REVIEW

**Comment by schneelittchen** [comment]
will be reviewed and tested once i'm back working on ve,
merci beaucoup

**Comment by UInt2048** [comment]
@schneelittchen No rush, but is there any way you can review this soon since you're working on it again?

**Comment by schneelittchen** [comment]
i review and accept other's code changes after i'm done with mine, which still are a few

**Comment by schneelittchen** [comment]
as expected my last and next upcoming change create(d) conflicts, sorry for the inconvenience

**Comment by UInt2048** [comment]
I've resolved the conflicts. I am currently using 1346bcc922db6a54da8a8fe1927e4f7a24cd64c3 without issue, but I haven't tested 5175ae508f9d7b8cf42fe29a290dd6f7c921e9b9, so please let me know if anything doesn't compile or if there's an apparent problem.

**Comment by schneelittchen** [comment]
i’ll try to get time to look at this tomorrow 🧘🏼‍♀️

**Comment by schneelittchen** [comment]
have to postpone it, need to update/release 12+ projects so i'm low on time (i also want to make myself a nice evening)

**Comment by thatcluda** [comment]
i just installed your fork on my device and don't get what it's supposed to do

**Comment by UInt2048** [comment]
@thatcluda Do the new settings it adds work?

Don't forget Ve does have settings. 😉

**Pull request closed without merging**
